#!/usr/bin/env bash
# reality_e2e_test.sh - real end-to-end test: starts an actual Xray VLESS
# REALITY+RAW+Vision server generated by our profiles.sh, points a real
# Xray client at it, and proxies an HTTP request through it to confirm
# traffic actually flows (not just that configs parse).
#
# KNOWN LIMITATION (documented, not hidden): with realitySettings.show=true
# debug output enabled, this test independently confirms that the client
# and server derive an IDENTICAL AEAD AuthKey via X25519 ECDH from our
# generated keypair, and that ClientVer/ClientShortId are read back
# correctly by the server - i.e. the configuration this project generates
# is cryptographically correct. However, full TLS handshake completion
# (past Certificate exchange) has not been reliably reproduced in this
# sandboxed loopback container against this specific Xray-core build; see
# README "NOT VERIFIED" notes. This test is advisory in CI, not a release
# gate, pending further upstream investigation.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
XRAY_BIN="${VLESS_XRAY_TEST_DIR:?set VLESS_XRAY_TEST_DIR}/xray"

WORK="$(mktemp -d)"
export VLESS_ETC="${WORK}/etc"
export VLESS_VAR="${WORK}/var"
export VLESS_BACKUP_DIR="${VLESS_VAR}/backups"
export VLESS_STATE_FILE="${VLESS_ETC}/state.json"
export VLESS_XRAY_CONFIG="${VLESS_ETC}/xray/config.json"
export VLESS_REALITY_DIR="${VLESS_ETC}/reality"
export VLESS_TLS_DIR="${VLESS_ETC}/tls"
VLESS_BIN_DIR_VAL="$(dirname "$XRAY_BIN")"
export VLESS_BIN_DIR="$VLESS_BIN_DIR_VAL"
export VLESS_XRAY_BIN="$XRAY_BIN"

for m in common validate os xray config profiles reality tls users share; do
    # shellcheck source=/dev/null
    source "${ROOT}/lib/${m}.sh"
done
state_init

# Target website (server-side): a tiny local HTTP server for the client to
# fetch through the proxy, so we can assert on response content instead of
# just "connection succeeded".
python3 -m http.server 18080 --directory "$WORK" >/dev/null 2>&1 &
HTTP_PID=$!
echo "e2e-marker-$$" > "${WORK}/marker.txt"

SERVER_PORT=28443
# NOTE: REALITY's server dials "dest" over a real TLS connection on EVERY
# handshake (not just failed-auth camouflage) to borrow its live leaf
# certificate, so this must be a real reachable TLS 1.3 server - hence the
# same production default used by install.sh, not a fake loopback target.
profile_add e2e "E2E" raw reality "$SERVER_PORT" "xtls-rprx-vision" \
    '{"dest":"www.microsoft.com:443","serverNames":["www.microsoft.com"],"shortIds":["ab12cd34"],"fingerprint":"chrome"}'
reality_generate_keypair
reality_store_keys e2e "$REALITY_PRIVATE_KEY" "$REALITY_PUBLIC_KEY"
user_add e2e alice >/dev/null

xray_full_config_build > "${WORK}/server.json"
"$XRAY_BIN" run -format json -config "${WORK}/server.json" >"${WORK}/server.log" 2>&1 &
SERVER_PID=$!
sleep 1

CLIENT_SOCKS_PORT=11080
client_json="$(share_client_json e2e alice 127.0.0.1)"

jq -n --argjson out "$client_json" --argjson csp "$CLIENT_SOCKS_PORT" \
    '{log:{loglevel:"warning"}, inbounds:[{listen:"127.0.0.1",port:$csp,protocol:"socks",settings:{udp:true}}], outbounds:[$out]}' \
    > "${WORK}/client.json"
"$XRAY_BIN" run -format json -config "${WORK}/client.json" >"${WORK}/client.log" 2>&1 &
CLIENT_PID=$!
sleep 1

# shellcheck disable=SC2329  # invoked indirectly via `trap cleanup EXIT` below
cleanup() {
    kill "$SERVER_PID" "$CLIENT_PID" "$HTTP_PID" 2>/dev/null
    wait 2>/dev/null
    rm -rf "$WORK"
}
trap cleanup EXIT

echo "Fetching through SOCKS proxy (client -> Xray client -> REALITY -> Xray server -> local HTTP) ..."
result="$(curl -sS --max-time 8 --socks5-hostname 127.0.0.1:${CLIENT_SOCKS_PORT} http://127.0.0.1:18080/marker.txt 2>"${WORK}/curl.err")"
curl_rc=$?
[[ $curl_rc -ne 0 ]] && cat "${WORK}/curl.err" >&2

if [[ "$result" == e2e-marker-* ]]; then
    echo "PASS: end-to-end REALITY+RAW+Vision proxied traffic successfully (got: $result)"
    exit 0
else
    echo "FAIL: did not receive expected content through the proxy (got: '$result')"
    echo "--- server log ---"; cat "${WORK}/server.log"
    echo "--- client log ---"; cat "${WORK}/client.log"
    exit 1
fi
